from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

class AgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="A list of messages exchanged between the user and the AI agent.")
    user_question : str = Field(..., description="The original question or prompt provided by the user for the AI agent to respond to.")
    curated_ques : str = Field(..., description="A curated question or prompt provided by the user for the AI agent to respond to.")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate a more accurate response.")
    is_safe : Literal["Yes", "No"] = Field(..., description="A flag indicating whether the generated response is safe or not. 'Yes' means the response is safe, while 'No' means it may contain unsafe content.")
    generated_sql_query : str = Field(..., description="The SQL query generated by the AI agent based on the provided prompt and context.")
    comments : str = Field(..., description="Additional comments or feedback provided by the AI agent regarding the generated SQL query and its execution.")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query against the database.")
    final_answer : str = Field(..., description="The final response generated by the AI agent after processing the prompt, context, and SQL query execution result.")

class JudgeSchema(BaseModel):
    answer : Literal["Yes", "No"] = Field(..., description="A flag indicating whether the judge's answer is affirmative or negative. 'Yes' means the judge approves, while 'No' means the judge does not approve.")
    comments : str = Field(..., description="Additional comments or feedback provided by the judge regarding the evaluation.")

class ETLAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the ETL agent")

class RouterSchema(BaseModel):
    answer: Literal["sql","etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")